Repository Laerdal/adapt_authoring, pull requests merged in 2024-10, with the labels that each got.

#79 Feature: added the new Template variable in en.json
  routes/lang/en.json
Labels: enhancement

#80 Fixed Authoring tool contextMenu dropdown is not showing fully showing
  frontend/src/modules/contextMenu/views/contextMenuView.js
Labels: bug

#86 Fix: Preserve HTML Tags in CKEditor
  frontend/src/modules/scaffold/backboneFormsOverrides.js
Labels: bug, enhancement

#87 Fix: Preserve HTML Tags in CKEditor
  frontend/src/modules/scaffold/backboneFormsOverrides.js
Labels: bug

#84 Add Notification Popups for Deprecated Plugins
  frontend/src/modules/navigation/views/navigationView.js
Labels: enhancement

#88 Feature: Plugin info popup message added in the manage extension view
  frontend/src/modules/editor/extensions/views/editorExtensionsEditView.js
  frontend/src/modules/navigation/views/navigationView.js
Labels: enhancement

#90 ADAPT-2654 : Fixed issue of CSS being duplicated while exporting the corses.
  lib/outputmanager.js
Labels: bug
