Repository Laerdal/adapt_authoring, pull requests merged in 2024-06, with the labels that each got.

#49 Preserve the HTML tags inserted into the CKEditor's source option.
  frontend/src/modules/scaffold/backboneFormsOverrides.js
Labels: enhancement

#50 Hotfix: Preserve html tags inserted in ck editor source option
  frontend/src/modules/scaffold/backboneFormsOverrides.js
Labels: hotfix

#52 Release: Adapt Sprint 90
  frontend/src/modules/help/index.js
  frontend/src/modules/scaffold/backboneFormsOverrides.js
Labels: release

#53 Release: Adapt Sprint 91
  plugins/output/adapt/outputHelpers.js
Labels: enhancement

#55 Release: Adapt Sprint 92
  frontend/src/modules/navigation/templates/navigation.hbs
  frontend/src/modules/support/index.js
Labels: release
