Repository Laerdal/adapt_authoring, pull requests merged in 2024-12, with the labels that each got.

#102 Feature: ADAPT-2918 : Added an feature to track the user inactivity for more than 1 hour.
  frontend/src/modules/user/index.js
  lib/configuration.js
Labels: enhancement

#103 Release: Adapt Sprint 104
  frontend/src/modules/editor/article/index.js
  frontend/src/modules/editor/article/views/editorArticleEditSidebarView.js
  frontend/src/modules/editor/block/index.js
  frontend/src/modules/editor/block/views/editorBlockEditSidebarView.js
  frontend/src/modules/editor/component/index.js
  frontend/src/modules/editor/component/views/editorComponentEditSidebarView.js
  frontend/src/modules/editor/contentObject/index.js
  frontend/src/modules/editor/contentObject/views/editorMenuItemView.js
  frontend/src/modules/editor/contentObject/views/editorMenuLayerView.js
  frontend/src/modules/editor/contentObject/views/editorPageArticleView.js
  frontend/src/modules/editor/contentObject/views/editorPageBlockView.js
  frontend/src/modules/editor/contentObject/views/editorPageComponentView.js
  frontend/src/modules/editor/contentObject/views/editorPageEditSidebarView.js
  frontend/src/modules/editor/contentObject/views/editorPageView.js
  frontend/src/modules/user/index.js
  lib/configuration.js
Labels: release

#105 Feature: Removed the Notify popup message
  frontend/src/modules/editor/extensions/views/editorExtensionsEditView.js
Labels: enhancement

#107 BugFix: ADAPT-3010-Revert the CKEditor5 changes
  frontend/src/modules/scaffold/backboneFormsOverrides.js
  frontend/src/modules/scaffold/less/textArea.less
  lib/configuration.js
  routes/index/index.hbs
Labels: bug

#108 Hotfix: Revert the CKEditor5 changes
  frontend/src/modules/scaffold/backboneFormsOverrides.js
  frontend/src/modules/scaffold/less/textArea.less
  lib/configuration.js
  routes/index/index.hbs
Labels: hotfix

#110 BugFix: ADAPT-2966 Theme Picker: Color Settings Not Fully Functional
  lib/outputmanager.js
Labels: bug
