Repository Laerdal/adapt_authoring, pull requests merged in 2024-09, with the labels that each got.

#67 New Icons for Templating management in the authoring tool
  frontend/src/modules/editor/contentObject/assets/templating-icons/Trash.svg
  frontend/src/modules/editor/contentObject/assets/templating-icons/downArrow.svg
  frontend/src/modules/editor/contentObject/assets/templating-icons/edit.svg
  frontend/src/modules/editor/contentObject/assets/templating-icons/leftArrow.svg
  frontend/src/modules/editor/contentObject/assets/templating-icons/rightArrow.svg
  frontend/src/modules/editor/contentObject/assets/templating-icons/upArrow.svg
Labels: enhancement

#69 Feature: Dynamic ID Updates Maintain Internal References for Course Components
  plugins/content/course/dbIndex.js
  plugins/content/course/index.js
Labels: enhancement

#71 Change the English translation text in the template management
  routes/lang/en.json
Labels: enhancement

#74 Release: WHO Adapt Sprint 98
  frontend/src/modules/editor/contentObject/assets/templating-icons/Trash.svg
  frontend/src/modules/editor/contentObject/assets/templating-icons/downArrow.svg
  frontend/src/modules/editor/contentObject/assets/templating-icons/edit.svg
  frontend/src/modules/editor/contentObject/assets/templating-icons/leftArrow.svg
  frontend/src/modules/editor/contentObject/assets/templating-icons/rightArrow.svg
  frontend/src/modules/editor/contentObject/assets/templating-icons/upArrow.svg
  plugins/content/course/dbIndex.js
  plugins/content/course/index.js
  plugins/output/adapt/importsource.js
  routes/lang/en.json
  routes/lang/es.json
Labels: release

#76 Fixed: Fixed the CKEditior is not loading correctly meaning that 'TextArea'
  frontend/src/modules/scaffold/backboneFormsOverrides.js
Labels: bug

#77 Hotfix: WHO CKEditor fix
  frontend/src/modules/scaffold/backboneFormsOverrides.js
  plugins/output/adapt/importsource.js
Labels: hotfix
