Repository Laerdal/adapt_authoring, pull requests merged in 2025-05, with the labels that each got.

#130 ADAPT-3175 Disable-the-extension-before-the-course-published
  plugins/output/adapt/publish.js
Labels: enhancement

#132 Feedback Label and Help Icon Overlap Slightly When Articles Are Toggled #131
  frontend/src/modules/contentPane/views/contentPaneView.js
  frontend/src/modules/editor/contentObject/views/editorPageArticleView.js
  routes/index/index.hbs
Labels: bug

#133 Provide feedback toggling articles moves the label issue #131
  frontend/src/modules/editor/contentObject/views/editorPageArticleView.js
Labels: bug

#134 Release: Adapt Sprint 115
  frontend/src/modules/contentPane/views/contentPaneView.js
  frontend/src/modules/editor/contentObject/views/editorPageArticleView.js
  plugins/output/adapt/publish.js
  routes/index/index.hbs
Labels: release
