Repository Laerdal/adapt_authoring, pull requests merged in 2025-02, with the labels that each got.

#119 Release: WHO Adapt Sprint 107
  CHANGELOG.md
  frontend/src/core/views/originView.js
  frontend/src/modules/editor/contentObject/views/editorMenuLayerView.js
  frontend/src/modules/editor/contentObject/views/editorPageBlockView.js
  frontend/src/modules/scaffold/backboneFormsOverrides.js
  frontend/src/modules/scaffold/less/textArea.less
  lib/configuration.js
  lib/outputmanager.js
  package-lock.json
  package.json
  plugins/output/adapt/importsource.js
  routes/index/index.hbs
Labels: release

#121 ADAPT-3063 Updated the Support Link
  frontend/src/modules/support/index.js
Labels: enhancement

#122 Hotfix: Update the Support Link on AT
  frontend/src/modules/support/index.js
Labels: hotfix

#124 Feature: ADAPT-3062 Implement the feedback link within the authoring tool
  routes/index/index.hbs
Labels: enhancement
