Repository Laerdal/adapt_authoring, pull requests merged in 2025-01, with the labels that each got.

#112 ADAPT-3013 : Fixed issue while import or export of courses after rena…
  lib/outputmanager.js
Labels: bug

#113 Release: Adapt Sprint 105
  frontend/src/modules/editor/contentObject/views/editorMenuLayerView.js
  frontend/src/modules/editor/contentObject/views/editorPageBlockView.js
  frontend/src/modules/editor/extensions/views/editorExtensionsEditView.js
  lib/outputmanager.js
Labels: release

#115 Fork issue/111
  lib/outputmanager.js
  plugins/output/adapt/importsource.js
Labels: bug

#116 Release: Adapt Sprint 106
  lib/outputmanager.js
  plugins/output/adapt/importsource.js
Labels: release

#117 Laerdal upgrade adapt authoring
  CHANGELOG.md
  frontend/src/core/views/originView.js
  frontend/src/modules/editor/article/views/editorArticleEditSidebarView.js
  frontend/src/modules/editor/contentObject/views/editorMenuItemView.js
  frontend/src/modules/editor/contentObject/views/editorPageBlockView.js
  frontend/src/modules/editor/contentObject/views/editorPageComponentView.js
  frontend/src/modules/scaffold/backboneFormsOverrides.js
  frontend/src/modules/scaffold/less/textArea.less
  lib/configuration.js
  package-lock.json
  package.json
  routes/index/index.hbs
Labels: enhancement
