Repository Laerdal/adapt_authoring, pull requests merged in 2025-07, with the labels that each got.

#144 Feature: ADAPT-3214 Markdown-to-HTML Conversion and optimize the code for AI Assistant
  frontend/src/libraries/marked.min.js
  frontend/src/modules/scaffold/backboneFormsOverrides.js
Labels: enhancement

#145 Feature: ADAPT- 3214 Hide the Replace button in CKEditor where it's not needed or relevant.
  frontend/src/modules/scaffold/backboneFormsOverrides.js
Labels: enhancement

#149 Feature : ADAPT-3214 Changed the tooltip position to top
  frontend/src/modules/scaffold/backboneFormsOverrides.js
Labels: enhancement

#152 Release: WHO Adapt Sprint 114 to 116
  frontend/src/modules/contentPane/views/contentPaneView.js
  frontend/src/modules/editor/contentObject/views/editorPageArticleView.js
  frontend/src/modules/scaffold/backboneFormsOverrides.js
  frontend/src/modules/user/models/sessionModel.js
  lib/auth.js
  lib/dml/schema/system/user.schema
  plugins/output/adapt/publish.js
  routes/index/index.hbs
Labels: release

#155 Hotfix: ADAPT-3175 Disable the Preview Edit extension on publish
  plugins/output/adapt/publish.js
Labels: hotfix

#156 Hotfix: ADAPT-3175 Disable the Preview Edit extension on publish
  plugins/output/adapt/publish.js
Labels: hotfix

#157 Release: Adapt Sprint 118
  plugins/filestorage/localfs/index.js
  plugins/output/adapt/export.js
  plugins/output/adapt/importsource.js
  plugins/output/adapt/importsourcecheck.js
  plugins/output/adapt/outputHelpers.js
  plugins/output/adapt/publish.js
Labels: release

#159 Dynamic ID Updates Preserve Internal References for Attempt Band Branching in Courses
  plugins/content/course/index.js
  plugins/output/adapt/importsource.js
Labels: enhancement
